// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMA2IfNiSRno1ibErpof6oMhFNCQnCHBI',
    appId: '1:724594242394:web:df92c98428ecddb9e7f963',
    messagingSenderId: '724594242394',
    projectId: 'vertical-mapper-445604-d7',
    authDomain: 'vertical-mapper-445604-d7.firebaseapp.com',
    storageBucket: 'vertical-mapper-445604-d7.firebasestorage.app',
    measurementId: 'G-CRK45BCB2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG2JXFYQ827r76Yr2ool-XfZk4J4at5Rw',
    appId: '1:724594242394:android:270cdd66dda1290fe7f963',
    messagingSenderId: '724594242394',
    projectId: 'vertical-mapper-445604-d7',
    storageBucket: 'vertical-mapper-445604-d7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMA2IfNiSRno1ibErpof6oMhFNCQnCHBI',
    appId: '1:724594242394:web:db3da27fd01ad940e7f963',
    messagingSenderId: '724594242394',
    projectId: 'vertical-mapper-445604-d7',
    authDomain: 'vertical-mapper-445604-d7.firebaseapp.com',
    storageBucket: 'vertical-mapper-445604-d7.firebasestorage.app',
    measurementId: 'G-6J68FLKT1L',
  );

}